language: python
python:
    - "2.7"
    - "2.6"
env:
    - CKANVERSION=master PGVERSION=9.1
    - CKANVERSION=2.3.1 PGVERSION=9.1
install:
    - ./bin/travis-build.bash
    - pip install coveralls
script: ./bin/travis-run.sh
services:
    - redis-server
after_success:
    - coveralls
